/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Napakalaki;
import javax.swing.JOptionPane;

/**
 *
 * @author roberto
 */
public class NapakalakiView extends javax.swing.JFrame {
    
    private Napakalaki napakalakiModel;
    private PlayerView aPlayer;
    
    public void setNapakalaki(Napakalaki napakalaki){
        this.napakalakiModel = napakalaki;
        player.removeAll();
        aPlayer = new PlayerView();
        aPlayer.setNapakalaki(this.napakalakiModel);
        aPlayer.setPlayer(this.napakalakiModel.getCurrentPlayer());
        aPlayer.setVisible(true);
        player.add(aPlayer);
        repaint();
        revalidate();
    }

    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player = new javax.swing.JPanel();
        monster = new javax.swing.JPanel();
        meetMonster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        nextTurn = new javax.swing.JButton();
        combat_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        monster.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        meetMonster.setText("Meet the monster");
        meetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterActionPerformed(evt);
            }
        });

        combat.setText("Combat");
        combat.setEnabled(false);
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        nextTurn.setText("Next Turn");
        nextTurn.setEnabled(false);
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meetMonster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextTurn))
                    .addComponent(combat_result))
                .addContainerGap(753, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(monster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combat_result)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meetMonster)
                    .addComponent(combat)
                    .addComponent(nextTurn)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        combat.setEnabled(false);
        nextTurn.setEnabled(true);
        aPlayer.enableButtons();
        
        switch(napakalakiModel.developCombat()){
            case WINGAME:
                combat_result.setText("Enhorabuena, has ganado la partida!");
                break;
            case WIN:
                combat_result.setText("Ganaste!");
                break;
            case LOSE:
                combat_result.setText("Perdiste! Te toca cumplir el mal rollo.");
                this.setNapakalaki(napakalakiModel);
                break;
            case LOSEANDCONVERT:
                combat_result.setText("Te conviertes en sectario! Perdiste.");
                this.setNapakalaki(napakalakiModel);
                break;
        }
    }//GEN-LAST:event_combatActionPerformed

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        if(napakalakiModel.nextTurn()){
            nextTurn.setEnabled(false);
            meetMonster.setEnabled(true);
            
            monster.removeAll();
            player.removeAll();
            combat_result.setText("");
            this.setNapakalaki(napakalakiModel);
        }else{
            JOptionPane.showMessageDialog(this, "Cumple tu mal rollo!");
        }
    }//GEN-LAST:event_nextTurnActionPerformed

    private void meetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterActionPerformed
        meetMonster.setEnabled(false);
        combat.setEnabled(true);
        
        MonsterView aMonster = new MonsterView();
        aMonster.setMonster(this.napakalakiModel.getCurrentMonster());
        aMonster.setVisible(true);
        monster.add(aMonster);
        aPlayer.disableButtons();
        
        repaint();
        revalidate();
    }//GEN-LAST:event_meetMonsterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JLabel combat_result;
    private javax.swing.JButton meetMonster;
    private javax.swing.JPanel monster;
    private javax.swing.JButton nextTurn;
    private javax.swing.JPanel player;
    // End of variables declaration//GEN-END:variables
}
